name: Deploy to Github Pages
on:
    push:
        branches:
            - chat

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome

    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 10.x
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli yarn
                yarn install
                yarn build
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: master
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}