name: Deploy to Github Pages
on:
    push:
        branches:
            - chat

jobs:
    build:
      timeout-minutes: 10
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [13.2.x]

        steps:
          - name: Run and test app
              run: |
                yarn install
                yarn build
                yarn start &
                yarn test
                yarn cypress:run
              env:
                CI: true

    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 10.x
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli yarn
                yarn install
                yarn build
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: master
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}